"""add_milestone_id_to_tasks

Revision ID: 9eb578cefdeb
Revises: 484b97e0165a
Create Date: 2025-05-01 15:54:07.498236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb578cefdeb'
down_revision: Union[str, None] = '484b97e0165a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('milestone_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'milestones', ['milestone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'milestone_id')
    # ### end Alembic commands ###
