name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      working-directory: ./frontend
      run: |
        # Check if package-lock.json exists, if not create it with npm install
        if [ ! -f "package-lock.json" ]; then
          npm install
        else
          npm ci
        fi
      
    - name: Run tests
      working-directory: ./frontend
      run: npm test
      
    - name: Run linting
      working-directory: ./frontend
      run: npm run lint
      
  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      working-directory: ./frontend
      run: |
        # Check if package-lock.json exists, if not create it with npm install
        if [ ! -f "package-lock.json" ]; then
          npm install
        else
          npm ci
        fi
      
    - name: Build
      working-directory: ./frontend
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build
        path: frontend/.next
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: frontend-build
        path: frontend/.next
        
    - name: Deploy to production
      run: |
        # Add your deployment steps here
        # For example, using SSH to connect to your server
        # and copying the build files
        echo "Deployment steps will be added here" 